### ISSUE TITLE
compile as shared-lib to .load from sqlite3-cli-tool

### ISSUE THREAD

**Issue by Asc2011** [niklaskorz/nim-exporttosqlite3#1]
Hello niklaskorz,
thx for these nice macros - they work really well. I could easily use procs from the wrapped snowball-stemmer-lib in nim. Now i'd like to compile these functions into a [Sqlite-extension](https://www.sqlite.org/loadext.html).
I've put the `registerfunctions()`-proc into the extension-entry-proc. This proc gets called by the sqlite3-cli with a sqlite-db-context. I pass this to the `registerfunction`, but it segfaults. 
This solution by [Chris Heller](https://forum.nim-lang.org/t/4782#57687) shows a entry-point-function.
I cannot make this solution work - seeing the same segfault when the nim-proc is registered to the SQLite-Api via `create_function` ?

greets Andreas

**Comment by Asc2011** [comment]
problem was hidden in a different module. Closing the issue now.

**Comment by niklaskorz** [comment]
Glad to see this could be resolved, feel free to re-open if there's anything else to do concerning this issue.
